#!/usr/bin/env bash
# This script installs Nginx and adds a custom X-Served-By header
apt-get update
apt-get install -y nginx
sed -i '0,/server_name _;/s||server_name _;\n\tadd_header X-Served-By $hostname;|' /etc/nginx/sites-available/default
service nginx restart

