#!/usr/bin/env bash
# This script installs and configures Nginx to serve "Holberton School"
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart

