#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirect for /redirect_me
apt-get update
apt-get install -y nginx
sed -i '0,/location \/ {/{s|location / {|location / {\n    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }|}' /etc/nginx/sites-available/default
service nginx restart
